# Generated by Django 6.0.6 on 2026-07-15 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FonoAppNoticias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FonoApp_Newsletter',
            fields=[
                ('id_suscripcion', models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo suscripcion')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo electrónico')),
                ('fecha_suscripcion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de suscripción')),
                ('estado', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Suscripción al Newsletter',
                'verbose_name_plural': 'Suscripciones al Newsletter',
                'db_table': 'FonoApp_Newsletter',
                'ordering': ['-fecha_suscripcion'],
                'managed': True,
            },
        ),
    ]
