# Generated by Django 6.0.6 on 2026-08-01 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PmCliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo registro cliente')),
                ('nombres_cliente', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellidos_clientes', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('rut_cliente', models.CharField(max_length=12, unique=True, verbose_name='RUT')),
                ('fecha_nacimiento_cliente', models.DateField(verbose_name='Fecha de nacimiento')),
                ('email_cliente', models.EmailField(max_length=254, unique=True, verbose_name='Correo electrónico')),
                ('telefono_cliente', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('estado', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Cliente del Portal Médico',
                'verbose_name_plural': 'Clientes del Portal Médico',
                'db_table': 'PmCliente',
                'ordering': ['-fecha_creacion'],
                'managed': True,
            },
        ),
    ]
