# Generated by Django 6.0.6 on 2026-08-09 18:52

import Security.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PmCliente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pmcliente',
            name='password_cliente',
            field=models.CharField(default='', max_length=128, verbose_name='Contraseña'),
        ),
        migrations.AlterField(
            model_name='pmcliente',
            name='rut_cliente',
            field=models.CharField(max_length=12, unique=True, validators=[Security.validators.validar_rut_chileno], verbose_name='RUT'),
        ),
        migrations.AlterField(
            model_name='pmcliente',
            name='telefono_cliente',
            field=models.CharField(max_length=20, validators=[Security.validators.validar_telefono], verbose_name='Teléfono'),
        ),
    ]
