# Generated by Django 6.0.6 on 2026-08-06 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('PmCliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PmVideo',
            fields=[
                ('id_video', models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo registro video')),
                ('video', models.FileField(upload_to='pm/videos/sintomas/', verbose_name='Video de síntomas')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción de los síntomas')),
                ('duracion_segundos', models.PositiveIntegerField(verbose_name='Duración en segundos')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de subida')),
                ('fecha_expiracion', models.DateTimeField(verbose_name='Fecha en que deja de estar disponible')),
                ('estado', models.BooleanField(default=True, verbose_name='Disponible')),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación')),
                ('motivo_eliminacion', models.CharField(blank=True, choices=[('VE', 'Vencimiento de los 30 días'), ('OM', 'Eliminado por orden del médico')], max_length=2, null=True, verbose_name='Motivo de la eliminación')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='PmCliente.pmcliente', verbose_name='Cliente que sube el video')),
            ],
            options={
                'verbose_name': 'Video de síntomas',
                'verbose_name_plural': 'Videos de síntomas',
                'db_table': 'PmVideo',
                'ordering': ['-fecha_subida'],
                'managed': True,
            },
        ),
    ]
