# Generated by Django 6.0.6 on 2026-08-12 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PmCita', '0001_initial'),
        ('PmVideo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pmvideo',
            name='cita',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='PmCita.pmcita', verbose_name='Cita a la que pertenece el video'),
        ),
    ]
