# Generated by Django 6.0.6 on 2026-08-09 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PmVideo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pmvideo',
            name='motivo_eliminacion',
            field=models.CharField(blank=True, choices=[('VE', 'Vencimiento de los 30 días'), ('OM', 'Eliminado por orden del médico'), ('RP', 'Retirado por el propio paciente')], max_length=2, null=True, verbose_name='Motivo de la eliminación'),
        ),
    ]
