# Generated by Django 6.0.6 on 2026-08-17 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PmVideo', '0002_alter_pmvideo_motivo_eliminacion'),
        ('PmVideo', '0002_pmvideo_cita'),
    ]

    operations = [
    ]
