# Generated by Django 6.0.6 on 2026-08-21 03:30

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PmVideo', '0003_merge_20260817_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pmvideo',
            name='video',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='video'),
        ),
    ]
