# Generated by Django 6.0.6 on 2026-06-26 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FonoAppInformacion', '0003_alter_fonoapp_informacion_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fonoapp_informacion',
            name='categoria',
            field=models.CharField(choices=[('PO', 'Promocion'), ('PE', 'Prevencion'), ('GE', 'general'), ('FA', 'farmacos')], default='GE', max_length=2, verbose_name='Categoría'),
        ),
    ]
