# Generated by Django 6.0.6 on 2026-08-21 03:30

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FonoAppInformacion', '0004_alter_fonoapp_informacion_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fonoapp_informacion_imagen',
            name='imagen',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='Imagen'),
        ),
    ]
