# Generated by Django 6.0.6 on 2026-08-28 04:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FonoApp_Diagnostico_Formulario',
            fields=[
                ('id_formulario', models.AutoField(primary_key=True, serialize=False, verbose_name='Código registro formulario')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del formulario')),
                ('descripcion', models.TextField(blank=True, verbose_name='Instrucciones para el paciente')),
                ('valor_minimo', models.PositiveSmallIntegerField(default=0, verbose_name='Valor mínimo de la escala')),
                ('valor_maximo', models.PositiveSmallIntegerField(default=4, verbose_name='Valor máximo de la escala')),
                ('estado', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('FonoApp_Administracion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formularios_diagnostico_registrados', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Formulario de diagnóstico',
                'verbose_name_plural': 'Formularios de diagnóstico',
                'db_table': 'FonoApp_Diagnostico_Formulario',
                'ordering': ['id_formulario'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FonoApp_Diagnostico_Respuesta',
            fields=[
                ('id_respuesta', models.AutoField(primary_key=True, serialize=False, verbose_name='Código registro resultado')),
                ('paciente_nombre', models.CharField(max_length=150, verbose_name='Nombre completo del paciente')),
                ('paciente_fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('fecha_diligenciamiento', models.DateField(auto_now_add=True, verbose_name='Fecha de diligenciamiento')),
                ('puntaje_total', models.PositiveIntegerField(default=0, verbose_name='Puntaje total')),
                ('detalle_subescalas', models.JSONField(blank=True, default=list, verbose_name='Puntaje por subescala')),
                ('FonoApp_Administracion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnosticos_aplicados', to=settings.AUTH_USER_MODEL, verbose_name='Aplicado por')),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='FonoAppDiagnostico.fonoapp_diagnostico_formulario')),
            ],
            options={
                'verbose_name': 'Resultado de test',
                'verbose_name_plural': 'Resultados de test',
                'db_table': 'FonoApp_Diagnostico_Respuesta',
                'ordering': ['-fecha_diligenciamiento', '-id_respuesta'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FonoApp_Diagnostico_Subescala',
            fields=[
                ('id_subescala', models.AutoField(primary_key=True, serialize=False, verbose_name='Código registro subescala')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la subescala')),
                ('orden', models.PositiveSmallIntegerField(default=0, verbose_name='Orden de despliegue')),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subescalas', to='FonoAppDiagnostico.fonoapp_diagnostico_formulario')),
            ],
            options={
                'verbose_name': 'Subescala',
                'verbose_name_plural': 'Subescalas',
                'db_table': 'FonoApp_Diagnostico_Subescala',
                'ordering': ['formulario', 'orden'],
                'managed': True,
                'unique_together': {('formulario', 'orden')},
            },
        ),
        migrations.CreateModel(
            name='FonoApp_Diagnostico_Pregunta',
            fields=[
                ('id_pregunta', models.AutoField(primary_key=True, serialize=False, verbose_name='Código registro pregunta')),
                ('texto', models.CharField(max_length=300, verbose_name='Enunciado de la pregunta')),
                ('orden', models.PositiveSmallIntegerField(default=0, verbose_name='Orden de despliegue')),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='FonoAppDiagnostico.fonoapp_diagnostico_formulario')),
                ('subescala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='FonoAppDiagnostico.fonoapp_diagnostico_subescala')),
            ],
            options={
                'verbose_name': 'Pregunta',
                'verbose_name_plural': 'Preguntas',
                'db_table': 'FonoApp_Diagnostico_Pregunta',
                'ordering': ['formulario', 'orden'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FonoApp_Diagnostico_RespuestaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.PositiveSmallIntegerField(verbose_name='Valor respondido')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='FonoAppDiagnostico.fonoapp_diagnostico_pregunta')),
                ('respuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='FonoAppDiagnostico.fonoapp_diagnostico_respuesta')),
            ],
            options={
                'verbose_name': 'Detalle de respuesta',
                'verbose_name_plural': 'Detalles de respuesta',
                'db_table': 'FonoApp_Diagnostico_RespuestaDetalle',
                'managed': True,
                'unique_together': {('respuesta', 'pregunta')},
            },
        ),
    ]
