# Generated by Django 6.0.6 on 2026-08-28 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FonoAppDiagnostico', '0002_alter_respuesta_administracion_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='fonoapp_diagnostico_respuesta',
            name='interpretacion_total',
            field=models.JSONField(blank=True, null=True, verbose_name='Interpretación del puntaje total'),
        ),
        migrations.CreateModel(
            name='FonoApp_Diagnostico_Interpretacion',
            fields=[
                ('id_interpretacion', models.AutoField(primary_key=True, serialize=False, verbose_name='Código registro interpretación')),
                ('valor_minimo', models.PositiveSmallIntegerField(verbose_name='Puntaje mínimo del rango')),
                ('valor_maximo', models.PositiveSmallIntegerField(verbose_name='Puntaje máximo del rango')),
                ('etiqueta', models.CharField(max_length=100, verbose_name='Resultado')),
                ('descripcion', models.TextField(blank=True, verbose_name='Recomendación para el paciente')),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interpretaciones', to='FonoAppDiagnostico.fonoapp_diagnostico_formulario')),
                ('subescala', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interpretaciones', to='FonoAppDiagnostico.fonoapp_diagnostico_subescala', verbose_name='Subescala (vacío = interpreta el puntaje total)')),
            ],
            options={
                'verbose_name': 'Interpretación de resultado',
                'verbose_name_plural': 'Interpretaciones de resultado',
                'db_table': 'FonoApp_Diagnostico_Interpretacion',
                'ordering': ['formulario', 'subescala', 'valor_minimo'],
                'managed': True,
            },
        ),
    ]
