# Generated by Django 6.0.6 on 2026-07-25 22:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FonoApp_InfoGeneral',
            fields=[
                ('id_info', models.AutoField(primary_key=True, serialize=False, verbose_name='Código registro información')),
                ('seccion', models.CharField(help_text='Ej: inicio, portal_cliente, footer', max_length=50)),
                ('clave', models.CharField(help_text='Identificador único. Ej: inicio_cuidados', max_length=50, unique=True)),
                ('titulo', models.CharField(blank=True, max_length=150, null=True, verbose_name='Título a mostrar')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Cuerpo del texto')),
                ('enlace', models.CharField(blank=True, max_length=255, null=True, verbose_name='URL o ruta del botón')),
                ('estado', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario_registro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='textos_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Información General',
                'verbose_name_plural': 'Información General',
                'db_table': 'FonoApp_InfoGeneral',
                'ordering': ['seccion', 'clave'],
            },
        ),
    ]
