# Generated by Django 6.0.6 on 2026-09-17 23:28

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('PmMedico', '0002_alter_pm_documento_respaldo_url_documento_profesional'),
    ]

    operations = [
        migrations.CreateModel(
            name='PmEjercicio',
            fields=[
                ('id_ejercicio', models.AutoField(primary_key=True, serialize=False, verbose_name='Código del ejercicio')),
                ('nombre', models.CharField(max_length=120, verbose_name='Nombre del ejercicio')),
                ('instrucciones', models.TextField(verbose_name='Cómo se hace')),
                ('video_ejemplo', cloudinary.models.CloudinaryField(max_length=255, verbose_name='video de ejemplo')),
                ('duracion_segundos', models.PositiveIntegerField(verbose_name='Duración del ejemplo en segundos')),
                ('estado', models.BooleanField(default=True, verbose_name='En el catálogo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejercicios', to='PmMedico.pm_profesional', verbose_name='Fonoaudiólogo dueño del ejercicio')),
            ],
            options={
                'verbose_name': 'Ejercicio de terapia',
                'verbose_name_plural': 'Ejercicios de terapia',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
