# Generated by Django 6.0.6 on 2026-09-21 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PmCita', '0003_pmcita_codigo_seguimiento'),
        ('PmCliente', '0002_pmcliente_password_cliente_and_more'),
        ('PmMedico', '0002_alter_pm_documento_respaldo_url_documento_profesional'),
        ('PmTerapia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PmPlanTerapia',
            fields=[
                ('id_plan', models.AutoField(primary_key=True, serialize=False, verbose_name='Código del plan')),
                ('periodicidad', models.CharField(choices=[('DIARIA', 'Diaria'), ('SEMANAL', 'Semanal'), ('QUINCENAL', 'Quincenal')], max_length=10)),
                ('fecha_inicio', models.DateField(verbose_name='Primer día del plan')),
                ('indicaciones', models.TextField(blank=True, default='', verbose_name='Indicaciones generales')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('CERRADO', 'Cerrado')], default='ACTIVO', max_length=10)),
                ('ultimo_periodo_recordado', models.IntegerField(default=-1)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('cita_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planes_terapia', to='PmCita.pmcita', verbose_name='Cita desde la que se creó')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_terapia', to='PmCliente.pmcliente', verbose_name='Paciente')),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_terapia', to='PmMedico.pm_profesional', verbose_name='Fonoaudiólogo')),
            ],
            options={
                'verbose_name': 'Plan de terapia',
                'verbose_name_plural': 'Planes de terapia',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='PmPlanEjercicio',
            fields=[
                ('id_plan_ejercicio', models.AutoField(primary_key=True, serialize=False, verbose_name='Código')),
                ('orden', models.PositiveSmallIntegerField(verbose_name='Orden en el plan (1 a 3)')),
                ('indicaciones', models.TextField(blank=True, default='', verbose_name='Indicaciones para este paciente')),
                ('estado', models.BooleanField(default=True, verbose_name='Forma parte del plan hoy')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones', to='PmTerapia.pmejercicio')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='PmTerapia.pmplanterapia')),
            ],
            options={
                'verbose_name': 'Ejercicio del plan',
                'verbose_name_plural': 'Ejercicios del plan',
                'ordering': ['orden'],
                'constraints': [models.UniqueConstraint(fields=('plan', 'ejercicio'), name='pmterapia_ejercicio_unico_por_plan')],
            },
        ),
    ]
