# Generated by Django 6.0.6 on 2026-09-21 17:53

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PmTerapia', '0002_pmplanterapia_pmplanejercicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='PmVideoProgreso',
            fields=[
                ('id_video', models.AutoField(primary_key=True, serialize=False, verbose_name='Código del video')),
                ('video', cloudinary.models.CloudinaryField(max_length=255, verbose_name='video')),
                ('duracion_segundos', models.PositiveIntegerField(verbose_name='Duración en segundos')),
                ('comentario', models.TextField(blank=True, default='', verbose_name='Comentario del paciente')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('fecha_expiracion', models.DateTimeField(verbose_name='Fecha en que deja de estar disponible')),
                ('numero_periodo', models.IntegerField(verbose_name='Periodo del plan al que pertenece')),
                ('retroalimentacion', models.TextField(blank=True, null=True)),
                ('fecha_retroalimentacion', models.DateTimeField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True, verbose_name='Disponible')),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
                ('motivo_eliminacion', models.CharField(blank=True, choices=[('VE', 'Vencimiento de los 7 días'), ('RP', 'Retirado por el propio paciente'), ('OM', 'Eliminado por orden del fonoaudiólogo')], max_length=2, null=True)),
                ('plan_ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='PmTerapia.pmplanejercicio', verbose_name='Ejercicio del plan al que responde')),
            ],
            options={
                'verbose_name': 'Video de progreso',
                'verbose_name_plural': 'Videos de progreso',
                'ordering': ['-fecha_subida'],
            },
        ),
    ]
