# Generated by Django 6.0.6 on 2026-08-12 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('PmCliente', '0001_initial'),
        ('PmMedico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PmCita',
            fields=[
                ('id_cita', models.AutoField(primary_key=True, serialize=False, verbose_name='Código cita')),
                ('fecha_hora', models.DateTimeField(verbose_name='Fecha y hora agendada')),
                ('duracion_minutos', models.PositiveIntegerField(default=45)),
                ('motivo_consulta', models.TextField(blank=True, null=True, verbose_name='Motivo de la consulta')),
                ('estado', models.CharField(choices=[('RE', 'Reservada'), ('CC', 'Cancelada por el cliente'), ('CM', 'Cancelada por el profesional'), ('RZ', 'Realizada')], default='RE', max_length=2)),
                ('permite_carga_video', models.BooleanField(default=True, verbose_name='Permite adjuntar video de síntomas')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('motivo_cancelacion', models.TextField(blank=True, null=True)),
                ('fecha_cancelacion', models.DateTimeField(blank=True, null=True)),
                ('cancelada_por', models.CharField(blank=True, choices=[('CLIENTE', 'Cliente'), ('PROFESIONAL', 'Profesional')], max_length=12, null=True)),
                ('fecha_hora_original', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y hora original, antes de la primera reprogramación')),
                ('veces_reprogramada', models.PositiveIntegerField(default=0)),
                ('motivo_reprogramacion', models.TextField(blank=True, null=True, verbose_name='Motivo de la última reprogramación')),
                ('reprogramada_por', models.CharField(blank=True, choices=[('CLIENTE', 'Cliente'), ('PROFESIONAL', 'Profesional')], max_length=12, null=True)),
                ('fecha_ultima_reprogramacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_marcada_realizada', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='PmCliente.pmcliente', verbose_name='Cliente que reserva')),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='PmMedico.pm_profesional', verbose_name='Profesional que atiende')),
            ],
            options={
                'verbose_name': 'Cita médica',
                'verbose_name_plural': 'Citas médicas',
                'db_table': 'PmCita',
                'ordering': ['-fecha_hora'],
                'managed': True,
            },
        ),
    ]
