# Generated by Django 6.0.6 on 2026-08-20 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PmCita', '0001_initial'),
        ('PmMedico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PmDisponibilidad',
            fields=[
                ('id_disponibilidad', models.AutoField(primary_key=True, serialize=False, verbose_name='Código disponibilidad')),
                ('fecha_hora', models.DateTimeField(verbose_name='Inicio del bloque')),
                ('duracion_minutos', models.PositiveIntegerField(default=45)),
                ('estado', models.BooleanField(default=True, verbose_name='Vigente')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cita', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disponibilidad', to='PmCita.pmcita', verbose_name='Cita que ocupa el bloque')),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades', to='PmMedico.pm_profesional', verbose_name='Profesional que ofrece la hora')),
            ],
            options={
                'verbose_name': 'Bloque de disponibilidad',
                'verbose_name_plural': 'Bloques de disponibilidad',
                'db_table': 'PmDisponibilidad',
                'ordering': ['fecha_hora'],
                'managed': True,
                'constraints': [models.UniqueConstraint(fields=('profesional', 'fecha_hora'), name='disponibilidad_unica_por_profesional_y_hora')],
            },
        ),
    ]
