# Generated by Django 6.0.6 on 2026-08-06 14:17

import Security.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('rut', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('estado', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Administrador (FonoApp)',
                'verbose_name_plural': 'Administradores (FonoApp)',
                'db_table': 'FonoApp_Administracion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PM_Especialidad',
            fields=[
                ('id_especialidad', models.AutoField(primary_key=True, serialize=False, verbose_name='Código especialidad')),
                ('nombre_especialidad_profesional', models.CharField(max_length=100, unique=True)),
                ('especialidad_requiere_certificado', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Especialidad',
                'verbose_name_plural': 'Especialidades',
                'db_table': 'PM_Especialidad',
                'ordering': ['nombre_especialidad_profesional'],
            },
        ),
        migrations.CreateModel(
            name='PM_Profesional',
            fields=[
                ('id_profesional', models.AutoField(primary_key=True, serialize=False, verbose_name='Código profesional')),
                ('nombres_profesional', models.CharField(max_length=100)),
                ('apellidos_profesional', models.CharField(max_length=100)),
                ('rut_profesional', models.CharField(max_length=12, unique=True, validators=[Security.validators.validar_rut_chileno])),
                ('numero_registro_salud_profesional', models.CharField(blank=True, default='', max_length=30)),
                ('email_profesional', models.EmailField(max_length=254, unique=True)),
                ('telefono_profesional', models.CharField(max_length=20, validators=[Security.validators.validar_telefono])),
                ('password_profesional', models.CharField(max_length=128)),
                ('estado_cuenta_profesional', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Profesional',
                'verbose_name_plural': 'Profesionales',
                'db_table': 'PM_Profesional',
                'ordering': ['apellidos_profesional', 'nombres_profesional'],
            },
        ),
        migrations.CreateModel(
            name='PM_Documento_Respaldo',
            fields=[
                ('id_documento', models.AutoField(primary_key=True, serialize=False, verbose_name='Código documento')),
                ('tipo_documeto_profesional', models.CharField(choices=[('CEDULA_IDENTIDAD', 'Cédula de identidad'), ('CERTIFICADO_TITULO', 'Certificado de título'), ('CERTIFICADO_SUPERINTENDENCIA', 'Certificado Superintendencia de Salud')], max_length=30)),
                ('url_documento_profesional', models.FileField(upload_to='pm_medico/documentos/%Y/%m/', validators=[Security.validators.validar_archivo_documento])),
                ('fecha_subida_documento_profesional', models.DateTimeField(auto_now_add=True)),
                ('documento_profesional_valido', models.BooleanField(default=False)),
                ('id_profesional', models.ForeignKey(db_column='id_profesional', on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='PmMedico.pm_profesional')),
            ],
            options={
                'verbose_name': 'Documento de respaldo',
                'verbose_name_plural': 'Documentos de respaldo',
                'db_table': 'PM_Documento_Respaldo',
                'ordering': ['-fecha_subida_documento_profesional'],
            },
        ),
        migrations.CreateModel(
            name='PM_Acreditacion',
            fields=[
                ('id_acreditacion', models.AutoField(primary_key=True, serialize=False, verbose_name='Código acreditación')),
                ('estado_verificacion_profesional', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_REVISION', 'En revisión'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=15)),
                ('fecha_solicitud_profesional', models.DateField(verbose_name='Fecha de solicitud')),
                ('fecha_resolucion_profesional', models.DateField(blank=True, null=True, verbose_name='Fecha de resolución')),
                ('id_administrador_resolutor', models.ForeignKey(blank=True, db_column='id_administrador_resolutor', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acreditaciones_resueltas', to='PmMedico.administrador')),
                ('id_profesional', models.ForeignKey(db_column='id_profesional', on_delete=django.db.models.deletion.CASCADE, related_name='acreditaciones', to='PmMedico.pm_profesional')),
            ],
            options={
                'verbose_name': 'Acreditación',
                'verbose_name_plural': 'Acreditaciones',
                'db_table': 'PM_Acreditacion',
                'ordering': ['-fecha_solicitud_profesional'],
            },
        ),
        migrations.CreateModel(
            name='PM_Profesional_especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('id_especialidad', models.ForeignKey(db_column='id_especialidad', on_delete=django.db.models.deletion.CASCADE, related_name='especialidad_profesionales', to='PmMedico.pm_especialidad')),
                ('id_profesional', models.ForeignKey(db_column='id_profesional', on_delete=django.db.models.deletion.CASCADE, related_name='profesional_especialidades', to='PmMedico.pm_profesional')),
            ],
            options={
                'verbose_name': 'Especialidad del profesional',
                'verbose_name_plural': 'Especialidades del profesional',
                'db_table': 'PM_Profesional_especialidad',
                'unique_together': {('id_profesional', 'id_especialidad')},
            },
        ),
        migrations.AddField(
            model_name='pm_profesional',
            name='especialidades',
            field=models.ManyToManyField(blank=True, related_name='profesionales', through='PmMedico.PM_Profesional_especialidad', to='PmMedico.pm_especialidad'),
        ),
    ]
