# Generated by Django 6.0.6 on 2026-08-21 03:30

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PmMedico', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pm_documento_respaldo',
            name='url_documento_profesional',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='documento'),
        ),
    ]
