# Generated by Django 6.0.6 on 2026-08-12 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FonoAppCuidados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fonoapp_cuidados',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación'),
        ),
    ]
