# Generated by Django 6.0.6 on 2026-08-21 03:30

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FonoAppCuidados', '0002_fonoapp_cuidados_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fonoapp_cuidados',
            name='img',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Imagen'),
        ),
    ]
