# Generated by Django 6.0.6 on 2026-07-30 02:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FonoApp_Voz',
            fields=[
                ('id_voz', models.AutoField(primary_key=True, serialize=False, verbose_name='Código registro voz')),
                ('categoria', models.CharField(choices=[('DEFINICION', 'Definición'), ('ANATOMIA', 'Anatomía'), ('FISIOLOGIA', 'Fisiología'), ('TRASTORNOS', 'Trastornos de la Voz'), ('IMPORTANCIA', 'Importancia del Cuidado'), ('CURIOSIDADES', 'Curiosidades')], default='DEFINICION', max_length=20, verbose_name='Categoría')),
                ('titulo', models.CharField(max_length=150, verbose_name='Título')),
                ('contenido', models.TextField(verbose_name='Contenido informativo sobre la voz')),
                ('img', models.ImageField(blank=True, null=True, upload_to='voz/imagenes/', verbose_name='Imagen')),
                ('fuente', models.URLField(blank=True, max_length=500, null=True, verbose_name='Fuentes Científicas')),
                ('estado', models.BooleanField(default=True, verbose_name='Activo')),
                ('FonoApp_Administracion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voz_registrada', to=settings.AUTH_USER_MODEL, verbose_name='Registrada por')),
            ],
            options={
                'verbose_name': 'Voz',
                'verbose_name_plural': 'Voz',
                'db_table': 'FonoApp_Voz',
                'ordering': ['id_voz'],
                'managed': True,
            },
        ),
    ]
