# Generated by Django 6.0.6 on 2026-06-26 17:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FonoAppAdministracion', '0002_fonoapp_administracion_last_conection'),
    ]

    operations = [
        migrations.CreateModel(
            name='FonoApp_Banner_Inicio',
            fields=[
                ('id_banner', models.AutoField(primary_key=True, serialize=False, verbose_name='Código registro banner')),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.TextField(verbose_name='Cuerpo del banner')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('estado', models.BooleanField(default=True, verbose_name='Activo')),
                ('FonoApp_Administracion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banners_registrados', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
                'db_table': 'FonoApp_Banner',
                'ordering': ['-fecha_creacion'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FonoApp_Banner_Inicio_Imagenes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='banner/imagenes/', verbose_name='Imagen')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='FonoAppAdministracion.fonoapp_banner_inicio')),
            ],
            options={
                'verbose_name': 'Imagen del banner',
                'verbose_name_plural': 'Imágenes del banner',
                'db_table': 'FonoApp_Banner_Imagen',
            },
        ),
    ]
