# Generated by Django 6.0.6 on 2026-08-21 03:30

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FonoAppAdministracion', '0003_fonoapp_banner_inicio_fonoapp_banner_inicio_imagenes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fonoapp_banner_inicio_imagenes',
            name='imagen',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='imagen'),
        ),
    ]
